extends:
  - re-taro
  - re-taro/next
  - re-taro/typescript
  - re-taro/prettier
  - plugin:storybook/recommended
rules:
  no-duplicate-imports: 0
  "@next/next/no-img-element": off
  no-secrets/no-secrets: off
parserOptions:
  project: ./tsconfig.json
