name: chromatic

on:
  workflow_run:
    workflows:
      - Chromatic test
    types:
      - completed

jobs:
  run-chromatic-deployment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        env:
          STORYBOOK_GOOGLE_MAP_API_KEY: ${{ secrets.STORYBOOK_GOOGLE_MAP_API_KEY }}
  run-chromatic-deployment-check:
    if: ${{ ! failure() }}
    needs: run-chromatic-deployment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publish Storybook is successfully executed."
