name: Light house

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  run-lighthouse-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable
      - name: production build
        run: yarn run build
      - name: install Lighthouse cli
        run: |
          npm install -g @lhci/cli@0.9.x
      - name: run Lighthouse cli
        id: lhci
        run: |
          mkdir lhci
          touch lhci/autorun.txt
          lhci autorun | grep 'storage.googleapis.com' > ./lhci/autorun.txt
          report_url=$(cat ./lhci/autorun.txt)
          echo $report_url
          echo "::set-output name=report_url::$report_url"
        continue-on-error: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: json to markdown
        uses: shoma3571/lhci-format-action@v1.3
        id: parse
        with:
          json-file-path: .lighthouseci/assertion-results.json
          report-url: ${{ steps.lhci.outputs.report_url }}
      - name: post comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./result-markdown.md "${URL}"
