name: ESLint

on:
  pull_request:
    branches:
      - dev

jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: eslint
        run: yarn run lint
