name: Prettier

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  run-prettier:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Format the code
        run: yarn run fmt
      - name: Auto commit
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "chore: コードを整形"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
  run-prettier-check:
    if: ${{ ! failure() }}
    needs: run-prettier
    runs-on: ubuntu-latest
    steps:
      - run: echo "Format is successfully executed."
