name: Test

on:
  pull_request:
    branches:
      - dev

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Check codes types
        run: yarn run type
      - name: Build the project
        run: yarn run build
      - name: Test
        run: yarn run test --no-cache
  run-test-check:
    if: ${{ ! failure() }}
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Type check, Build, Test are successfully executed."
