name: 'figma-tokens style-dictionary actions'
on:
  pull_request:

jobs:
  generate_scss:
    name: generate_scss
    runs-on: ubuntu-latest
    # 'figma' という名前を含むブランチのみ動くように設定
    if: contains(github.head_ref, 'figma')
    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: yarn add -D style-dictionary
        run: yarn add -D style-dictionary

      - name: run style-dictionary
        run: yarn style-dictionary build

      - name: add and commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: generate scss by style-dictionary
