name: figma-tokens style-dictionary actions

on:
  workflow_run:
    workflows:
      - figma-tokens test
    types:
      - completed

jobs:
  generate_json:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable
      - name: run style-dictionary
        run: yarn run gen:style
      - name: Auto commit
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "feat: design tokenから_variable.jsonの生成"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
